---
- hosts: consul-master
  become: true
  roles:
    - role: consul
      consul_config: 
        bind_addr: "{{ IPADDRESS }}"
        server: true
        ui: true
        bootstrap_expect: 1
     

